apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-user
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: nginx-user
  minReplicas: 1
  maxReplicas: 10
  metrics:
      resource:
        name: cpu
        targetAverageUtilization: 70
  cooldownSeconds: 300
