apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apache-shift
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-shift
  minReplicas: 1
  maxReplicas: 10
  metrics:
      resource:
        name: cpu
        targetAverageUtilization: 70
  cooldownSeconds: 300
