apiVersion: v1
kind: Service
metadata:
  name: apache-shift
  namespace: default
spec:
  selector:
    app: apache-shift
  type: LoadBalancer
  ports:
  - name: apache-shift
    protocol: TCP
    port: 3080
    targetPort: 8080
    nodePort: 30080
